src/state.dia

Progress on state.dia

---

src/state.dia

1st draft version of state.dia

---

src/state.dia

design pattern State machine

---

src/state.dia

design pattern State machine Context:Game

---

src/state.dia

added two  handle and request

---

src/state.dia

added handle1 and 2 concrete state

added handle1 and 2 concrete state

---

src/state.dia

modified concrete states

---

src/state.dia

name player

---

src/state.dia

modified player

---

src/client/main.cpp
src/shared/state/GameConfig.cpp

Mabranche2

---

src/state.dia

added getContents to statedia and playerList in GameConfig

added getContents to statedia and playerList in GameConfig

---

src/shared/state/GameConfig.cpp
src/state.dia

finished Gameconfig and added getContents

finished Gameconfig and added getContents

---

src/shared/state/Player.cpp

modified player destr

---

src/shared/state/Resources.cpp
src/state.dia

modified getType as virtual in dia

modified getType as virtual in dia

---

src/shared/state/Playing.cpp

tiles initialization

---

src/shared/state/Game.cpp
src/shared/state/Playing.cpp
src/state.dia

modif Playing.cpp handle2, Game.cpp

modif Playing.cpp handle2, Game.cpp

---

src/shared/state/Playing.cpp

added Playing.cpp Game Loop logic

added Playing.cpp Game Loop logic

---

src/shared/state/ActionCard.cpp
src/shared/state/Game.cpp
src/shared/state/Player.cpp
src/shared/state/Playing.cpp
src/state.dia

continued cards and boathold implementation with .csv file

continued cards and boathold implementation with .csv file

---

src/shared/state/ActionCard.cpp
src/shared/state/BoatHold.cpp
src/shared/state/Game.cpp
src/shared/state/Player.cpp
src/shared/state/Playing.cpp

continued boatHold + cardDeck

---

src/client.dia
src/client/client/InputHandler.cpp
src/shared/state/Player.cpp

player.cpp shuffle and choosecard => inputhandler

player.cpp shuffle and choosecard => inputhandler

---

src/shared/state/Player.cpp

playturn structure

---

src/shared/state/Player.cpp

playturn() : checkcombat() is inside actionprocessor()

playturn() : checkcombat() is inside actionprocessor()

---

src/shared/state/Player.cpp
src/shared/state/PlayingState.cpp
src/state.dia

chooseOpponent, checkcombat

---

src/shared/state/PlayingState.cpp

playingstate handle2 mistake

---

src/shared/state/Player.cpp

player.cpp refactored comment

---

src/shared/engine/CombatManager.cpp
src/shared/state/Player.cpp

player.cpp et combatmanager.cpp

player.cpp et combatmanager.cpp

---

src/shared/engine/CombatManager.cpp
src/state.dia

state.dia et combatmanager

---

src/engine.dia

engine.dia chooseoponent

---

src/engine.dia
src/shared/state/Player.cpp

engine.dia et player chooseoponent

engine.dia et player chooseoponent

---

src/shared/engine/CombatManager.cpp

combatmanager.cpp

---

src/engine.dia
src/shared/engine/CombatManager.cpp
src/shared/state/Game.cpp
src/shared/state/Player.cpp

correction d'erreur

---

src/shared/state/Player.cpp

player chooseopponent

---

src/client/client/Client.cpp
src/shared/engine/AssignDice.cpp
src/shared/engine/DiceManager.cpp

cut DiceManager paste Client

---

src/shared/engine/MovePlayer.cpp
src/shared/state/Game.cpp
src/state.dia

begin moveplayer command

---

src/shared/engine/GameEngine.cpp
src/shared/state/Game.cpp

game loop and moveplayer command

game loop and moveplayer command

---

src/shared/engine/GameEngine.cpp

game engine oubli

---

src/shared/engine/GameEngine.cpp
src/shared/engine/MapManager.cpp
src/shared/engine/MovePlayer.cpp
src/shared/state/Game.cpp
src/shared/state/GameConfigState.cpp

begin refactor game loop

---

src/shared/engine/GameEngine.cpp
src/shared/state/CardActionState.cpp
src/shared/state/GameConfigState.cpp

continue cardactionstate

---

src/shared/engine/GameEngine.cpp
src/shared/state/CardActionState.cpp

cardActionState activeplayerindex

cardActionState activeplayerindex

---

src/shared/engine/GameEngine.cpp
src/shared/state/CardActionState.cpp

gameengine and cardactionstate

gameengine and cardactionstate

---

src/client.dia
src/client/client/Client.cpp
src/client/client/InputHandler.cpp

our first command call

---

src/client/client/Client.cpp

player name and mapsize commands

player name and mapsize commands

---

src/engine.dia
src/shared/engine/ChooseNbOfPlayers.cpp

added command destructors

---

src/shared/engine/AddToBoathold.cpp
src/shared/engine/AssignDice.cpp
src/shared/engine/ChooseCanons.cpp
src/shared/engine/ChooseCard.cpp
src/shared/engine/ChooseMapSize.cpp
src/shared/engine/ChooseOpponent.cpp
src/shared/engine/ChoosePath.cpp
src/shared/engine/ChoosePlayerName.cpp
src/shared/engine/RollDice.cpp
src/shared/engine/StealResource.cpp

commands destructor

---

src/shared/engine/ResourceManager.cpp
src/shared/engine/StealResource.cpp

stealResource command

---

src/IA.dia

began IA.dia

---

src/ai.dia
src/state.dia

began ai.dia

---

src/client/client/Client.cpp
src/shared/state/GameConfigState.cpp

cleaning client, gameconfigstate

cleaning client, gameconfigstate

---

src/client/client/Client.cpp
src/client/client/InputHandler.cpp
src/shared/state/CardActionState.cpp
src/shared/state/GameConfigState.cpp
src/state.dia

continued switch state client

---

src/client/client/Client.cpp
src/shared/state/CardActionState.cpp

continued cardactionstate

---

src/client/client/Client.cpp
src/shared/state/CardActionState.cpp

continued cardactionstate in client

continued cardactionstate in client

---

src/client/client/Client.cpp
src/shared/state/CardActionState.cpp
src/shared/state/GameConfigState.cpp
src/shared/state/ResourceHandlingState.cpp

corrected error and continued cardactionstate

corrected error and continued cardactionstate

---

src/client/client/Client.cpp
src/shared/state/ResourceHandlingState.cpp

resourcehandlingstate

---

src/shared/state/Player.cpp

error correction

---

src/shared/state/Player.cpp
src/shared/state/ResourceHandlingState.cpp
src/state.dia

continued resourcehandlingstate

continued resourcehandlingstate

---

src/client/client/Client.cpp

client corr

---

src/client/client/Client.cpp
src/shared/state/Player.cpp
src/shared/state/ResourceHandlingState.cpp
src/state.dia

continued paying in client  and resourcehandlingstate

continued paying in client  and resourcehandlingstate

---

src/client/client/Client.cpp
src/shared/state/ResourceHandlingState.cpp

resourcehandlingstate + client to modify

resourcehandlingstate + client to modify

---

src/client/client/Client.cpp
src/shared/state/Player.cpp
src/shared/state/ResourceHandlingState.cpp
src/state.dia

working on Action-related states

working on Action-related states

---

src/client/client/Client.cpp
src/shared/state/Player.cpp
src/shared/state/ResourceHandlingState.cpp

moving players

---

src/client/client/Client.cpp
src/shared/state/OpponentChoiceState.cpp
src/shared/state/Player.cpp
src/shared/state/ResourceHandlingState.cpp

working on selectboathold and removeresource

working on selectboathold and removeresource

---

src/client.dia
src/client/client/Client.cpp
src/client/client/InputHandler.cpp
src/shared/state/OpponentChoiceState.cpp
src/shared/state/Player.cpp
src/shared/state/ResourceHandlingState.cpp
src/state.dia

needs debug : implemented some of ResourceHandlingState
make OK

needs debug : implemented some of ResourceHandlingState

---

src/client/client/InputHandler.cpp
src/shared/state/ResourceHandlingState.cpp

corrected player position after movement

corrected player position after movement

---

src/client.dia
src/client/client/Client.cpp
src/client/client/InputHandler.cpp
src/shared/state/OpponentChoiceState.cpp
src/shared/state/Player.cpp
src/shared/state/ResourceHandlingState.cpp

opponent choice

---

src/client/client/Client.cpp
src/shared/engine/RollDice.cpp
src/shared/state/CombatAttackingState.cpp
src/shared/state/CombatDefendingState.cpp
src/shared/state/Game.cpp
src/shared/state/OpponentChoiceState.cpp
src/shared/state/ResourceHandlingState.cpp

commit du soir: attacking and defending in client

commit du soir: attacking and defending in client

---

src/client.dia
src/client/client/Client.cpp
src/client/client/InputHandler.cpp
src/shared/engine/StealResource.cpp
src/shared/state/CombatAttackingState.cpp
src/shared/state/CombatDefendingState.cpp
src/shared/state/Game.cpp
src/shared/state/StealResourceState.cpp
src/state.dia

stealresourcestate, attacking, defending

stealresourcestate, attacking, defending
